### ISSUE TITLE
Database locked error

### ISSUE THREAD

**Issue by Mikez333** [yubiuser/pihole_adlist_tool#1]
So I ran the script using bash, and it said Error: database is locked. I think I'm running it wrong.

**Comment by yubiuser** [comment]
Thanks for reporting the issue.

I don't think you're running it wrong - the syntax is quite easy
` ./pihole_adlist_tool`

As pihole and the script both access `gravity.db` and `pihole-FTL.db` there might be concurrency access attempts.

Does the output say which database is locked?

Steps you could try:
1. run the script again (maybe it was just bad timing for you and pihole accessing the databases at the same time)
2. run with fewer days to analyze ` ./pihole_adlist_tool -d 30`
3. increase the timeout (time to wait if a database lock is detected in line 122
`sqlite3 -cmd ".timeout 5000" $TEMP_DB << EOF`
4. last resort: copy `pihole-FTL.db` and `gravity.db` to another place and change the paths at the beginning of the script accordingly

**Comment by yubiuser** [comment]
Closed due to no further details were provided.
