### ISSUE TITLE
Errors encountered

### ISSUE THREAD

**Issue by Danp2** [yubiuser/pihole_adlist_tool#12]
Thanks for the nice tool! It runs for me, but appears to encounter a few issues. Here's a portion of the output --

```
  [i]  Calculating.....
  [i]  This might take some time - please be patient.
Error: near line 10: no such column: COUNT
Error: near line 11: no such column: COUNT
Error: near line 12: no such column: COUNT

  [i]  You have 9 adlists configured (5 enabled)
  [i]  Your gravity.db contains 157966 unique domains
  [i]  Since 22.12.2020 10:25:22 1108 different domains from your adlists have been blocked 336922 times in total
       (blocked directly by gravity or during deep CNAME inspection)
  [i]  Using you current adlist configuration 1316 domains would have been blocked 440581 times


  Press enter to continue...
./pihole_adlist_tool: line 557: [: : integer expression expected
./pihole_adlist_tool: line 577: [: : integer expression expected
```

Pi-hole is running on a Ubuntu 20.04 VM and was just updated today to the latest version ( Pi-hole v5.2.4 Web Interface v5.3.1 FTL v5.5.1)

Any idea on why these errors are occurring?

**Comment by yubiuser** [comment]
Thanks for the report.

I haven't upgraded to the latest version yet but there should be changes that would break the script. 
Did it work before the upgrade?

What version of `sqlite` do you run?

`Error: near line 10: no such column: COUNT`
It's the first time I see this issue and I'm not sure if it is related to the script. `Count` should be treated as an function, not as a column name.

**Comment by Danp2** [comment]
Thanks for the quick response. Here's the sqlite into --
```
k# sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
```

Unsure if the script ran on pi-hole before upgrade. I can restore an earlier version and test it.

**Comment by yubiuser** [comment]
The version is not outdated.

>Unsure if the script ran on pi-hole before upgrade. I can restore an earlier version and test it.

This would be great.

**Comment by Danp2** [comment]
Error occurs on the earlier version as well.

```
    Pi-hole v5.2.3 · Update available! Web Interface v5.3 · Update available! FTL v5.4 · Update available! 
```

**Comment by Danp2** [comment]
Guessing that the errors are coming from this section of code --

```
sqlite3 $TEMP_DB << EOF
    INSERT INTO unique_domains(domain, adlist_id) SELECT domain, adlist_id FROM gravity_strip GROUP BY domain HAVING COUNT(domain)==1 order by adlist_id asc;
    UPDATE adlist SET domains_covered=(select count(domain) FROM gravity_strip WHERE id== adlist_id GROUP BY adlist_id);
    UPDATE adlist SET hits_covered=(SELECT SUM(blocked_domains.hits) FROM gravity_strip JOIN blocked_domains ON gravity_strip.domain == blocked_domains.domain WHERE id== adlist_id Group by adlist_id);
    UPDATE adlist SET unique_domains_covered=(SELECT COUNT(domain) FROM unique_domains WHERE adlist_id==id GROUP BY adlist_id);

    INSERT INTO info (property, value) Select 'NUM_ADLISTS', COUNT(id) FROM adlist; 
    INSERT INTO info (property, value) Select 'NUM_ADLISTS_ENABLED', COUNT(id) FROM adlist WHERE enabled==1;
    INSERT INTO info (property, value) Select 'NUM_DOMAINS_BLOCKED_CURRENT', COUNT(domain) FROM blocked_domains; 
    INSERT INTO info (property, value) Select 'HITS_TOTAL_CURRENT', SUM(hits) FROM blocked_domains;
    INSERT INTO info (property, value) Select 'BLACKLIST_GRAVITY', COUNT FROM blacklist_gravity;
    INSERT INTO info (property, value) Select 'NUM_TOTAL_UNIQUE_DOMAINS', COUNT FROM unique_domains;
    INSERT INTO info (property, value) Select 'BLACKLIST_CNAME', COUNT FROM blacklist_cname;
.exit
EOF
```

Is the syntax correct where COUNT is used without any further qualifiers?

**Comment by Danp2** [comment]
FWIW, errors appear to be resolved by changing `COUNT FROM` to `COUNT(*) FROM`

**Comment by Danp2** [comment]
Looking at the original code, I now see that it is already correct. Not sure how I ended up with something else. 😦

**Comment by yubiuser** [comment]
Thanks for investigating. Sorry to hear that your code was changed/messed up. Did you figure out why it was changed? It's strange that only the `(*)` is removed.
