### ISSUE TITLE
Dnsmasq 2.84

### ISSUE THREAD

**Issue by Neustradamus** [yubiuser/pihole_adlist_tool#16]
@yubiuser: Can you update to 2.84?
- http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q1/014640.html

There was a bug in Dnsmasq 2.83.

Changelog:
- http://www.thekelleys.org.uk/dnsmasq/CHANGELOG

**Comment by yubiuser** [comment]
Thanks for the info. However, I will not force users to run 2.8.4 (yet). Reasons
1. A pihole-FTL version which includes dnsmasq 2.8.4 has not been released yet. Thus, forcing this version will prevent anyone from using this script.
2. Dnsmasq 2.8.4 contains mostly a fix of a regression, no new security related fixes. I don't want to force users to upgrade just for that
3. The new pihole-FTL version will most likely not contain any improvements that are relevant for this script.
