### ISSUE TITLE
pihole_adlist_tool .. start probleme ^^

### ISSUE THREAD

**Issue by sk2eu** [yubiuser/pihole_adlist_tool#20]
Bin also wegen [der](https://discourse.pi-hole.net/t/pihole-adlist-tool-wie-wird-das-installiert/44805) Installation Routine hier .. 

Und frage mich was soll passieren nachdem ich starten will.. 

pi@ras:~ $ chmod +x ./pihole_adlist_tool
pi@ras:~ $
pi@ras:~ $ ./pihole_adlist_tool
-bash: ./pihole_adlist_tool: Is a directory
pi@ras:~ $ /pihole_adlist_tool
-bash: /pihole_adlist_tool: No such file or directory

https://ibb.co/wRzCwzz

**Comment by yubiuser** [comment]
Durch das `git clone` wurde ein Verzeichnis `pihole_adlist_tool` angelegt, in das du erst wechseln musst, dann nochmal `chmod` ausfürhen.

```
cd pihole_adlist_tool
chmod +x ./pihole_adlist_tool
./pihole_adlist_tool
```

**Comment by sk2eu** [comment]
Hey ... noch mal ich ..  scheint zu gehen hat alles importiert.  habe jetzt 4.3 millionen domains .. 

und du hast das alles nur mit wenig programierkenntnissen gemacht ? da steht am ende sowas in der art geschrieben .. ist wohl schon ein wenig untertreiben ? wie weiss ich dass dieses tool die auswertung meiner domains nicht weiterleitet ? 

sendet das tool was raus ?

**Comment by yubiuser** [comment]
> Hey ... noch mal ich .. scheint zu gehen hat alles importiert. habe jetzt 4.17 millionen domains ..

Das Skript importiert nichts, sondern analysiert nur. Es sollte keine Domains hinzufügen.

> und du hast das alles nur mit wenig programierkenntnissen gemacht ? da steht am ende sowas in der art geschrieben .. ist wohl schon ein wenig untertreiben ?

Naja, ich habe mit wenig angefangen und dann ist das Skript immer größer geworden. Halt alles in der Freizeit. Wenn man lange genug in der Linux-Welt unterwegs ist, kommen die meisten wahrscheinlich dazu, gewisse Funktionen in Skripte zu packen, dabei lernt man halt auch etwas Programmieren.

> wie weiss ich dass dieses tool die auswertung meiner domains nicht weiterleitet ?
> sendet das tool was raus ?

Nein, tut es nicht. Der Quellcode liegt offen (nämlich im Skript selbst), du kannst dir also einfach ansehen, was das Skript an welcher Stelle macht. Ein paar Kommentare stehen auch drin. Wenn du den Quellcode nicht verstehst, musst du mir das halt einfach glauben.
