### ISSUE TITLE
würde gerne das Script nutzen brauchen aber hilfe.

### ISSUE THREAD

**Issue by fredop89** [yubiuser/pihole_adlist_tool#21]
Hi, ich würde gerne das pihole adlist tool nutzen /ausprobieren. habe allergings keinen plan wo ich da anfangen soll/wie das geht.

**Comment by yubiuser** [comment]
Also prinzipielle funktioniere es so: du lädst dir das Skript herunter, machst es "ausführbar" und startest es dann. Es ist ein Kommandozeilen Skript, sodass du auch dort arbeiten musst.
Schau mal [hier](https://github.com/yubiuser/pihole_adlist_tool/issues/20), da hatte jemand die gleiche Frage. Sieh mal, wie weit du kommst und dann melde dich einfach nochmal.

**Comment by fredop89** [comment]
ok, also ich brauche putty? und gebe dort dann Login daten für Phiole und dann (chmod +x ./pihole_adlist_tool) ein? ich frage mich wie ich das gedownloadete aufs Pinole bekomme  oder passiert das Automatisch?

**Comment by yubiuser** [comment]
Ja, du musst dich auch deinem Pi-hole Gerät einloggen (wenn du Windows verwendest, dann z.B. mit Putty.)

Download mit

`git clone https://github.com/yubiuser/pihole_adlist_tool.git`

dann ins Verzeichnis wechseln
`cd pihole_adlist_tool`

Ausführbar machen
`chmod +x ./pihole_adlist_tool`

und starten
`./pihole_adlist_tool`

**Comment by fredop89** [comment]
Ok das hat anscheinend Funktioniert. Danke. jetzt soll ich wählen zwischen 1-4?1)  Keep all adlists enabled
  2)  Enable only adlists with covered unique domains
  3)  Enable the minimal number of adlists that cover all domains that would have been blocked
  4)  Restore previous adlist configuration

  Please select:   Please select:   Please select: ./pihole_adlist_tool: line 683: read: ++++++++ Info ++++                                                                                                                                  ++++: ++: assignment requires lvalue (error token is "++++++++")

  [i]  Removing temporary database...
  [✓]  Temporary database removed

**Comment by yubiuser** [comment]
>jetzt soll ich wählen zwischen 1-4

Ja, da musst du eine Auswahl treffen.

**Comment by fredop89** [comment]
ich schätze dann 3 wäre das wofür das scribt da ist?

**Comment by yubiuser** [comment]
Das Skript lässt dir die Auswahl, du musste selbst anhand der Informationen, die es dir zur Verfügung stellt, entscheiden wofür du es verwenden willst. Nummer 3 ist halt eine Option.

**Comment by yubiuser** [comment]
Hat es geklapp?

**Comment by fredop89** [comment]
Ich hab jetzt auf gut glück eine Auswahl getroffen,  es wurden ein paar listen  Deaktiviert.  Ich habe ab und zu noch Seiten wo ich drauf will die aber geblockt werden.

**Comment by yubiuser** [comment]
Schön, dass es funktioniert.
