### ISSUE TITLE
Starting with version 2.4.0, you get multiple 'environment: line 5: docker: command not found' messages

### ISSUE THREAD

**Issue by Andr3Carvalh0** [yubiuser/pihole_adlist_tool#28]
Am still checking what's happening here, but it seems that somewhere in the script the docker command gets called when it shouldn't (and as end result no changes get applied).

**Other info:**

- The script detects/sets PIHOLE_DOCKER to 0 (when it should).
- To reproduce the bug run the script with 0 params and pick option 1(Current adlist configuration) followed by 3 (Enable the minimal number of adlists that cover all domains that would have been blocked).
- I think this might be happening due to `SUDO_SQLITE`. Am assuming the value of `PIHOLE_DOCKER` doesnt stay/is visible when we call `SUDO_SQLITE`, but am really not sure.

**Comment by yubiuser** [comment]
Confirm the bug. 

> I think this might be happening due to SUDO_SQLITE. Am assuming the value of PIHOLE_DOCKER doesnt stay/is visible when we call SUDO_SQLITE, but am really not sure.

I guess that's what happend.

**Comment by yubiuser** [comment]
Pushed a fix, would be happy if you could try it.

**Comment by Andr3Carvalh0** [comment]
Just try it. Seems to be working 😄
