### ISSUE TITLE
"SUDO_SQLITE: command not found"

### ISSUE THREAD

**Issue by DJF3** [yubiuser/pihole_adlist_tool#30]
>   1)  Keep all adlists enabled
>   2)  Enable only adlists with covered unique domains
>   3)  Enable the minimal number of adlists that cover all domains that would have been blocked
>   4)  Restore previous adlist configuration
> 
>   Please select: 2
> 
>   [i]  Enabling adlists with covered unique domains....
> bash: 0=0: command not found
> bash: **SUDO_SQLITE: command not found**
> bash: sqlite: command not found
> bash: 0=0: command not found
> bash: SUDO_SQLITE: command not found
> bash: sqlite: command not found
> bash: 0=0: command not found
> bash: SUDO_SQLITE: command not found
> bash: sqlite: command not found
>   [✓] Reloading DNS lists
> 
>   [✓]  Adlists with covered unique domains enabled
> 
> 
>   [✓]  Of the 833 domains that would have been blocked by the adlist configuration you chose to analyze,
>        0 domains are covered by your current adlist configuration.
> 
>   [i]  Removing temporary database...
>   [✓]  Temporary database removed

**Note that:**
$ sqlite
> -bash: sqlite: command not found

$ sqlite3
> SQLite version 3.27.2 2019-02-25 16:06:06
> Enter ".help" for usage hints.

So I created an alias "sqlite='sqlite3'"  but that did not solve the error message.
How would I be able to fix this? 

I'm also a bit worries about the message: 
>   [✓]  Of the 833 domains that would have been blocked by the adlist configuration you chose to analyze,
>        0 domains are covered by your current adlist configuration.

Does this mean that there's domains _not_ covered (833) that should be covered?

**Comment by yubiuser** [comment]
Something is wrong here. Which version of the script are you running? Are you running Pi-hole bare metal or on docker?

**Comment by DJF3** [comment]
Version: downloaded today
Pi-Hole running on a raspberry with Rasbian 10.6 Buster
Looking at the code there's no need to create an alias for 'sqlite'

**Comment by yubiuser** [comment]
Thanks for the report. This was a typo in the end (`$` was at the wrong spot). Should be fixed now.
