### ISSUE TITLE
Regex Mode does not work in docker

### ISSUE THREAD

**Issue by vali-m** [yubiuser/pihole_adlist_tool#34]
When running the command 
`./pihole_adlist_tool -d 0 -r`
It gets into an infinite loop (even starting to heat up the raspberry pi 4) saying the same error over and over again:
`./pihole_adlist_tool: line 987: pihole-FTL: command not found`

Full logs are attached:
[pihole_adlist_tool_docker_error.txt](https://github.com/yubiuser/pihole_adlist_tool/files/7874788/pihole_adlist_tool_docker_error.txt)

**Comment by yubiuser** [comment]
Thanks for your report. This is a known bug.
https://github.com/yubiuser/pihole_adlist_tool/issues/24

I currently don't run Pi-hole in docker. Need to find time to sit down and set it up and fix this

**Comment by thomasmerz** [comment]
@yubiuser  - I'm working on a fix for this… seems to be quite simple, but I need some more tests…
