### ISSUE TITLE
Wrong detection of PIHOLE_DOCKER?!

### ISSUE THREAD

**Issue by thomasmerz** [yubiuser/pihole_adlist_tool#35]
I executed `docker exec -it pihole bash` and then:
```
root@pihole-merz-nimbus:/etc/pihole# ./pihole_adlist_tool
  *** Pihole Adlist Tool 2.6 ***
   ++++++++ Info ++++++++
  [i]  PIHOLE_DOCKER: No
  [i]  PIHOLE_DNSMASQ_VERSION: 2.87test4-18
  [i]  SQLITE_VERSION: 3.37.1
  [i]  DAYS_REQUESTED: 30
  [i]  TOP: Not shown
  [i]  SORT_ORDER: id ASC
  [i]  UNIQUE: Not shown
  [i]  REGEX_MODE: Disabled
  [i]  There is an update available: 2.6.0
…
```

So I can say for sure that this Pi-Hole is running within Docker 😆  But your really nice script is detecting this wrong/not.

Also the update-detection is not correct - or version of 2.6 is set wrong and should be 2.6.0!?

**Comment by yubiuser** [comment]
> Also the update-detection is not correct - or version of 2.6 is set wrong and should be 2.6.0!?

It's only a string comparison. I should have set the version to 2.6.0 ;-)
___

What's the output of

```
command -v docker

docker ps -q -f status="running" -f name="pihole"

docker ps -f "name=pihole" -q

```

**Comment by yubiuser** [comment]
> docker exec -it pihole bash

Wait: do you try to run the script within the container? It is not designed to run inside the container (my guess is it will work, but docker detection works only from the outside). It needs to be run on the host system.

**Comment by thomasmerz** [comment]
> What's the output of
```
🦎🖥  ✔ ~/dev/docker-pi-hole/etc-pihole [master|✚ 1…7]
21:22 $ command -v docker
/usr/bin/docker
🦎🖥  ✔ ~/dev/docker-pi-hole/etc-pihole [master|✚ 1…7]
21:22 $ docker ps -q -f status="running" -f name="pihole"
e7f0ac55094f
🦎🖥  ✔ ~/dev/docker-pi-hole/etc-pihole [master|✚ 1…7]
21:22 $ docker ps -f "name=pihole" -q
e7f0ac55094f
```

**Comment by thomasmerz** [comment]
> It is not designed to run inside the container

Ok, **that** explains everything 😆 

```
🦎🖥  ✔ ~/dev/docker-pi-hole/etc-pihole [master|✚ 1…7]
21:24 $ ./pihole_adlist_tool -d 7 -t 100 -r -u


  *** Pihole Adlist Tool 2.6 ***


   ++++++++ Info ++++++++

  [i]  PIHOLE_DOCKER: Yes
…
```

**Comment by thomasmerz** [comment]
But… outside my docker container it works much worse 😢 
`./pihole_adlist_tool: line 987: pihole-FTL: command not found` (repeated many hundred times!)

**Comment by yubiuser** [comment]
https://github.com/yubiuser/pihole_adlist_tool/issues/24

**Comment by thomasmerz** [comment]
YMMV - for me it works **perfectly** 💋  😆

**Comment by pluim003** [comment]
I can confirm that it's running fine from within the Docker-container even better than from outside the container.
