### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mike2246** [yubiuser/pihole_adlist_tool#46]
How do you install/run this?

**Comment by yubiuser** [comment]
https://github.com/yubiuser/pihole_adlist_tool/issues/9

**Comment by mike2246** [comment]
I get ./pihole_adlist_tool is a directory

**Comment by yubiuser** [comment]
change into the directory
`cd pihole_adlist_tool`

make the script executable
`chmod +x ./pihole_adlist_tool`

and start it
`./pihole_adlist_tool`
