### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by thorrrr** [yubiuser/pihole_adlist_tool#58]
HI 
Please can you tell me how i install and run this?

**Comment by yubiuser** [comment]
https://github.com/yubiuser/pihole_adlist_tool/issues/9#issuecomment-718979344

**Comment by thorrrr** [comment]
HI 
Thank you for your link
I have a query i have run it and somewhat confused.
I have run gravity before using the script and it says fully successful.
But your script keeps saying i have a issue 43 to 41
Also when i answer any of the questions it is just ignored!!!

https://logs.notifiarr.com/?f15797c82a881d46#Buu9bXf1tkJTjUtKRHon1Xsb3Q9LFC4RBnUr7LtXSHvg

**Comment by yubiuser** [comment]
> Also when i answer any of the questions it is just ignored!!!

Well, what should I say? You're running the script in `automatic` mode.

```
pi@pihole-dns-01:~/pihole_adlist_tool $ ./pihole_adlist_tool -a
  [i]  Running in automatic mode, keeping current adlist configuration.
  [i]  Running in automatic mode, not running gravity.
  [i]  Running in automatic mode, keeping current adlist configuration.
```
____

> But your script keeps saying i have a issue 43 to 41

Two of your lists don't contain any domains.

```
id   enabled  total_domains  domains_covered  hits_covered  unique_domains_covered  address
---  -------  -------------  ---------------  ------------  ----------------------  --------------------------------------------------------------------------------------------------------------------------------------
7    1        0                                                                     https://www.malwaredomainlist.com/hostslist/hosts.txt
11   1        0                                                                     https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt

```
