### ISSUE TITLE
[Recommendation] - Make Current Adlist Default Option

### ISSUE THREAD

**Issue by thebiggeek** [yubiuser/pihole_adlist_tool#6]
Thank you for making this wonderful tool, I noticed that after you run the tool, an option relating to Analysis of Either All or Current Adlist comes up. This could either be (A) Defaults to 5 seconds to automatically select current or (B) be available only if Interactive mode has been used to run the script.

**Comment by yubiuser** [comment]
> (A) Defaults to 5 seconds to automatically select current or (B) be available only if Interactive mode has been used to run the script.

The script has only an interactive mode (nothing happens automatically so far) - I want the users to see the numbers and make an informed decision about the quality of their lists.

That leaves only room for possibility (A).

What would be the benefit for a default selection?

**Comment by yubiuser** [comment]
Closing due to no reaction. Feel free to open again.
