### ISSUE TITLE
Can't read /etc/pihole/pihole-FTL.db

### ISSUE THREAD

**Issue by cberg18** [yubiuser/pihole_adlist_tool#64]
When pihole_adlist_tool I get the following output: 

```
~/pihole_adlist_tool (master) --ϐ ./pihole_adlist_tool                                                                                   


  *** Pihole Adlist Tool 2.6.3 ***


   ++++++++ Info ++++++++

  [i]  PIHOLE_DOCKER: No
  [i]  PIHOLE_DNSMASQ_VERSION: v2.87
  [i]  SQLITE_VERSION: 3.39.2
  [i]  DAYS_REQUESTED: 30
  [i]  TOP: Not shown
  [i]  SORT_ORDER: id ASC
  [i]  UNIQUE: Not shown
  [i]  REGEX_MODE: Disabled

   ++++++++++++++++++++++



  [i]  Warning: You requested to analyze the last 30 day(s) (starting from 14.09.2022	19:56:48),
       but last query is from 31.12.1969	17:00:00
  [i]  Nothing to do here. Exiting 
```
Running 
```
pihole-FTL sqlite3 "file:/etc/pihole/pihole-FTL.db" "SELECT MIN(timestamp) FROM queries;"
```
or
```
pihole-FTL sqlite3 "file:/etc/pihole/pihole-FTL.db" "SELECT MAX(timestamp) FROM queries;"
```

by itself returns nothing, so I believe that there's an issue with the command getting data from the db. 

Output of pihole_adlist_tool -v
```
~/pihole_adlist_tool (master) --ϐ ./pihole_adlist_tool -v                                                                                
Pihole Adlist Tool v2.6.3
```

**Comment by yubiuser** [comment]
> so I believe that there's an issue with the command getting data from the db.

There is no issue with the command, there is an issue with your long-term database.  That's why it says "Can't read /etc/pihole/pihole-FTL.db"

Please open a help topic on Pi-hole's discourse forum and provide a debug token there.
https://discourse.pi-hole.net/c/bugs-problems-issues/11

**Comment by cberg18** [comment]
Nowhere does it say "Can't read /etc/pihole/pihole-FTL.db", it doesn't return any data for the queries used.

**Comment by yubiuser** [comment]
It says so in your issue title.

**Comment by yubiuser** [comment]
But anyway, this is not an issue with the tool, but with your database.

**Comment by cberg18** [comment]
Cool, thanks for your help
