### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by Knuschberkeks** [yubiuser/pihole_adlist_tool#78]
There doesn't seem to be a licence attached to this repo. In this state no one would be allowed to publish a derivative work, or even copy the code for a personal project. This might be an intentional, but usually it's an oversight. Quick read up on licenses [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license).

**Comment by yubiuser** [comment]
Fixed now by https://github.com/yubiuser/pihole_adlist_tool/pull/86
