### ISSUE TITLE
List the domains which generated a hit

### ISSUE THREAD

**Issue by xternaal** [yubiuser/pihole_adlist_tool#79]
Hey,
Thanks so much for your tool, it allowed me to really streamline my lists.

I was wondering if you might be able to help with another issue. I am trying to figure out a way to see which domains have triggered in each list.
I have a malware list loaded and it is really difficult to figure out which domains are being triggered on my network. Using the pihole webgui there is no way to search for blocked domains by list.

I thought with some tweaking your tool might be able to do that? 

This is my output when I run the tool with -a

`[i]  Adlist coverage

id  enabled  total_domains  domains_covered  hits_covered  unique_domains_covered  address                                                         
--  -------  -------------  ---------------  ------------  ----------------------  ----------------------------------------------------------------
1   1        209627         593              60232         589                     https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
5   1        167912         1                2                                     https://v.firebog.net/hosts/RPiList-Malware.txt                  `

I want to know what the domain is that is listed against the malware list so I can search for it in the webgui to find out which client triggered the hit

Many thanks

**Comment by yubiuser** [comment]
I think I can help. The script creates a temporary database in ``/temp/temp.db`` which gets deleted at the end of the run. 

https://github.com/yubiuser/pihole_adlist_tool/blob/a1ed479c4aaf367ecca8afa6e0ae4d26f029170a/pihole_adlist_tool#L1079

Comment or delet this last line and run the script again. The temp database should stay and you can use a tool like https://sqlitebrowser.org/ to inspect and interact with it. I don't know the exact database structure out of my head righ now, but you should be able to find what you are looking for. I think it should be in `´gravity_strip `` table, but not exactly sure.

**Comment by xternaal** [comment]
Wow thank you so much that is awesome. 

I loaded the database and on the browse data tab, I just selected gravity_strip and then you can filter based on the adlist_id.

**Comment by thomasmerz** [comment]
@yubiuser , this should be closed because the problem has been solved by your help.
